labels:
  platform: linux/amd64

steps:
  publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: gitea.elara.ws
      repo: elara6331/seashell
      tags: latest,${CI_COMMIT_TAG}
      cache: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: tag
  
  release:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    secrets: [ gitea_token, aur_key ]
    when:
      event: tag